config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get "customers/index"
  put "customers/update"
  devise_for :customers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "contacts/index"
  get "abouts/index"
  root to: "home#index"
  resources :tags
  resources :colors
  resources :products do
    collection do
      get "search"
    end
  end
  resources :brands
  resources :product_types
  resources :categories
  resources :carts
  # /checkout/create something
  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
  has_one_attached :image

  validates :name, presence: true, uniqueness: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: true
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :product_colors
  has_many :products, through: :product_colors

  validates :name, presence: true, uniqueness: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :province, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :order_status

  validates :session_id, presence: true, uniqueness: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order

  validates :item_name, :order_price, :order_quantity, presence: true
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :brand
  belongs_to :product_type
  has_many :product_colors
  has_many :colors, through: :product_colors
  has_many :product_tags
  has_many :tags, through: :product_tags
  accepts_nested_attributes_for :product_tags, allow_destroy: true

  validates :name, :description, :price, presence: true
  validates :name, uniqueness: true
  validates :price, numericality: { format: { with: /\A\d+(\.\d{2})?\z/ } }
  validates :rating, numericality: { format: { with: /\A\d+(\.\d{2})?\z/ } }
end

app/models/product_color.rb
class ProductColor < ApplicationRecord
  belongs_to :product
  belongs_to :color

  validates :product_id, uniqueness: { scope: :color_id }
end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
  belongs_to :product
  belongs_to :tag

  validates :product_id, uniqueness: { scope: :tag_id }
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: true
end

app/models/province.rb
class Province < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :gst, :hst, :qst, :pst, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :product_tags
  has_many :products, through: :product_tags

  validates :name, presence: true, uniqueness: true
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :set_product_type, only: %i[show edit update destroy]

  # GET /product_types or /product_types.json
  def index
    @product_types = ProductType.order("name ASC").page(params[:page]).per(10)
  end

  # GET /product_types/1 or /product_types/1.json
  def show
    @product_type = ProductType.find(params[:id])
  end

  # GET /product_types/new
  def new
    @product_type = ProductType.new
  end

  # GET /product_types/1/edit
  def edit; end

  # POST /product_types or /product_types.json
  def create
    @product_type = ProductType.new(product_type_params)

    respond_to do |format|
      if @product_type.save
        format.html do
          redirect_to product_type_url(@product_type),
                      notice: "Product type was successfully created."
        end
        format.json { render :show, status: :created, location: @product_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_types/1 or /product_types/1.json
  def update
    respond_to do |format|
      if @product_type.update(product_type_params)
        format.html do
          redirect_to product_type_url(@product_type),
                      notice: "Product type was successfully updated."
        end
        format.json { render :show, status: :ok, location: @product_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1 or /product_types/1.json
  def destroy
    @product_type.destroy

    respond_to do |format|
      format.html do
        redirect_to product_types_url, notice: "Product type was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product_type
    @product_type = ProductType.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_type_params
    params.require(:product_type).permit(:name)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/product_types/_form.html.erb
<%= form_with(model: product_type) do |form| %>
  <% if product_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product_type.errors.count, "error") %> prohibited this product_type from being saved:</h2>

      <ul>
        <% product_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit class: "btn btn-outline-primary mt-2 mb-3" %>
  </div>
<% end %>

app/views/product_types/_product_type.html.erb
<div class="container mt-3" id="<%= dom_id product_type %>">
  <h1>
    <strong>
      <%= product_type.name %>
    </strong>
  </h1>
  <h3>Products by Product Type (Order by Rating)</h3>
  <table class="table">
    <%= render partial: 'layouts/components/theadproduct' %>
    <tbody>
      <%= render partial: 'layouts/components/tbodyproduct', collection: product_type.products.order("rating DESC"), as: :product %>
    </tbody>
  </table>
</div>

app/views/product_types/edit.html.erb
<div class="container mt-3">

  <h1>Editing product type</h1>

  <%= render "form", product_type: @product_type %>

  <%= link_to "Show this product type", @product_type, class: "btn btn-outline-primary" %>
  <%= link_to "Back to product types", product_types_path, class: "btn btn-outline-primary" %>
</div>

app/views/product_types/index.html.erb
<div class="container mt-3" id="product_type">
  <h1>Product Types</h1>
  <% unless (paginate @product_types).present? %>
    <br><br>
  <% end %>
  <div class="d-flex justify-content-end">
    <%= paginate @product_types %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th style="width: 30%">Product Type Name</th>
        <th>Products in Product Type</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @product_types.each do |product_type| %>
        <tr>
          <td>
            <%= product_type.name %>
          </td>
          <td>
            <%= product_type.products.count %>
          </td>
          <td>
            <%= link_to "Show Products", product_type, class: "btn btn-outline-primary" %>
          </td>
          <td>
            <%= link_to "Edit", edit_product_type_path(product_type), class: "btn btn-outline-success" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "New product type", new_product_type_path, class: "btn btn-outline-primary" %>
</div>

app/views/product_types/new.html.erb
<div class="container mt-3">

  <h1>New product type</h1>

  <%= render "form", product_type: @product_type %>

  <%= link_to "Back to product types", product_types_path, class: "btn btn-outline-primary" %>
</div>

app/views/product_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product_type %>

<div class="container mt-3">
  <%= link_to "Edit this product type", edit_product_type_path(@product_type), class: "btn btn-outline-primary" %>
  <%= link_to "Back to product types", product_types_path, class: "btn btn-outline-primary" %>

  <%= button_to "Destroy this product type", @product_type, method: :delete, class: "btn btn-outline-danger mt-3" %>
</div>