config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get "customers/index"
  put "customers/update"
  devise_for :customers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "contacts/index"
  get "abouts/index"
  root to: "home#index"
  resources :tags
  resources :colors
  resources :products do
    collection do
      get "search"
    end
  end
  resources :brands
  resources :product_types
  resources :categories
  resources :carts
  # /checkout/create something
  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
  has_one_attached :image

  validates :name, presence: true, uniqueness: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: true
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :product_colors
  has_many :products, through: :product_colors

  validates :name, presence: true, uniqueness: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :province, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :order_status

  validates :session_id, presence: true, uniqueness: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order

  validates :item_name, :order_price, :order_quantity, presence: true
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :brand
  belongs_to :product_type
  has_many :product_colors
  has_many :colors, through: :product_colors
  has_many :product_tags
  has_many :tags, through: :product_tags
  accepts_nested_attributes_for :product_tags, allow_destroy: true

  validates :name, :description, :price, presence: true
  validates :name, uniqueness: true
  validates :price, numericality: { format: { with: /\A\d+(\.\d{2})?\z/ } }
  validates :rating, numericality: { format: { with: /\A\d+(\.\d{2})?\z/ } }
end

app/models/product_color.rb
class ProductColor < ApplicationRecord
  belongs_to :product
  belongs_to :color

  validates :product_id, uniqueness: { scope: :color_id }
end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
  belongs_to :product
  belongs_to :tag

  validates :product_id, uniqueness: { scope: :tag_id }
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: true
end

app/models/province.rb
class Province < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :gst, :hst, :qst, :pst, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :product_tags
  has_many :products, through: :product_tags

  validates :name, presence: true, uniqueness: true
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  before_action :set_color, only: %i[show edit update destroy]

  # GET /colors or /colors.json
  def index
    @colors = Color.order("name ASC").page(params[:page]).per(10)
  end

  # GET /colors/1 or /colors/1.json
  def show
    @color = Color.find(params[:id])
  end

  # GET /colors/new
  def new
    @color = Color.new
  end

  # GET /colors/1/edit
  def edit; end

  # POST /colors or /colors.json
  def create
    @color = Color.new(color_params)

    respond_to do |format|
      if @color.save
        format.html { redirect_to color_url(@color), notice: "Color was successfully created." }
        format.json { render :show, status: :created, location: @color }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colors/1 or /colors/1.json
  def update
    respond_to do |format|
      if @color.update(color_params)
        format.html { redirect_to color_url(@color), notice: "Color was successfully updated." }
        format.json { render :show, status: :ok, location: @color }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colors/1 or /colors/1.json
  def destroy
    @color.destroy

    respond_to do |format|
      format.html { redirect_to colors_url, notice: "Color was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_color
    @color = Color.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def color_params
    params.require(:color).permit(:name)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/colors/_color.html.erb
<div  class="container mt-3" id="<%= dom_id color %>">
  <h1>
    <strong>
      <%= color.name %>
    </strong>
  </h1>
  <h3>Products by Color (Order by Rating)</h3>
  <table class="table">
    <%= render partial: 'layouts/components/theadproduct' %>
    <tbody>
      <%= render partial: 'layouts/components/tbodyproduct', collection: color.products.order("rating DESC"), as: :product %>
    </tbody>
  </table>
</div>

app/views/colors/_form.html.erb
<%= form_with(model: color) do |form| %>
  <% if color.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(color.errors.count, "error") %> prohibited this color from being saved:</h2>

      <ul>
        <% color.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit class: "btn btn-outline-primary mt-2 mb-3" %>
  </div>
<% end %>

app/views/colors/edit.html.erb
<div class="container mt-3">

  <h1>Editing color</h1>

  <%= render "form", color: @color %>

  <%= link_to "Show this color", @color, class: "btn btn-outline-primary"  %>
  <%= link_to "Back to colors", colors_path, class: "btn btn-outline-primary"  %>
</div>

app/views/colors/index.html.erb
<div class="container mt-3" id="colors">
  <h1>Colors</h1>
  <% unless (paginate @colors).present? %>
    <br><br>
  <% end %>
  <div class="d-flex justify-content-end">
    <%= paginate @colors %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th style="width: 30%">Color Name</th>
        <th>Products in Color</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @colors.each do |color| %>
        <tr>
          <td>
            <%= color.name %>
          </td>
          <td>
            <%= color.products.count %>
          </td>
          <td>
            <%= link_to "Show Products", color, class: "btn btn-outline-primary" %>
          </td>
          <td>
            <%= link_to "Edit", edit_color_path(color), class: "btn btn-outline-success" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "New color", new_color_path, class: "btn btn-outline-primary" %>
</div>

app/views/colors/new.html.erb
<div class="container mt-3">
  <h1>New color</h1>

  <%= render "form", color: @color %>


  <%= link_to "Back to colors", colors_path, class: "btn btn-outline-primary"  %>
</div>

app/views/colors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @color %>

<div class="container mt-3">
  <%= link_to "Edit this color", edit_color_path(@color), class: "btn btn-outline-primary" %>
  <%= link_to "Back to colors", colors_path, class: "btn btn-outline-primary" %>

  <%= button_to "Destroy this color", @color, method: :delete, class: "btn btn-outline-danger mt-3" %>
</div>